title: Kathryn Reeve
tagline: Senior & Lead Developer
description: Kathryn Reeve, Senior & Lead PHP / Laravel Developer. Edinburgh, Scotland.
url: https://binarykitten.com
email: Kathryn@BinaryKitten.com
location: Edinburgh, Scotland. UK
github: BinaryKitten

exclude:
  - fpr-checker.sh
  - README
  - "*.pdf"
